# Generated by Django 5.2.7 on 2025-10-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_personaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('COURSE', 'Course'), ('EXAM', 'Exam')], default='COURSE', max_length=10),
        ),
    ]
