# Generated by Django 5.2.7 on 2025-10-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_certificate_file_alter_certificate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
