# Generated by Django 5.2.7 on 2025-11-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_course_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Course', 'Course'), ('Exam', 'Exam')], default='COURSE', max_length=10),
        ),
    ]
